### ISSUE TITLE
Errors at startup and unable to open Editor

### ISSUE THREAD

**Issue by guptadivyansh** [mathworks-ref-arch/matlab-dockerfile#73]
I installed matlab to an Ubuntu 22 machine using matlab package manager (mpm). I activated it and can launch the executable, but I get this error as soon as matlab starts:

```
java.lang.RuntimeException: Dynamic exception type: std::runtime_error
std::exception::what: Did not start the server. Desired port was: 31515. Last error was: Port is not available for address: 127.0.0.1:31614

	at com.mathworks.matlabserver.connector.impl.ConnectorImpl.doNativeEnsureServiceOn(Native Method)
	at com.mathworks.matlabserver.connector.impl.ConnectorImpl.doEnsureServiceOn(ConnectorImpl.java:231)
	at com.mathworks.matlabserver.connector.api.Connector.ensureServiceOn(Connector.java:150)
	at com.mathworks.mde.liveeditor.plugins.execution.LiveEditorExecutionDockingManager.<init>(LiveEditorExecutionDockingManager.java:35)
	at com.mathworks.mde.liveeditor.plugins.execution.LiveEditorExecutionDockingManager.getInstance(LiveEditorExecutionDockingManager.java:25)
	at com.mathworks.mde.liveeditor.LiveEditorInitializationManager.initialize(LiveEditorInitializationManager.java:26)
	at com.mathworks.mde.desk.MLDesktop$7$1.run(MLDesktop.java:919)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I can run scripts and execute single commands in the command window, but trying to install addons throws the same error as above. I also cannot launch the editor:

![Screenshot 2023-07-27 at 14 30 45](https://github.com/mathworks-ref-arch/matlab-dockerfile/assets/9139390/d88e93bf-97e7-46d3-8887-b12f0e472f34)

Any idea why this might be happening? I already activated the license with the activate_matlab.sh script.

**Comment by guptadivyansh** [comment]
I had to reinstall Ubuntu for another reason and installed Matlab normally via GUI. This installation works without any issues.
